import type { AttractionItem, RestaurantItem, TransportItem } from "./types";

export const MOCK_ATTRACTIONS: AttractionItem[] = [
  {
    id: "a-1",
    name: "Registon Majmuasi",
    cityName: "Samarqand",
    categoryKey: "historical",
    categoryDefault: "Tarixiy Obida",
    description: "XV-XVII asrlarga oid 3 ta muhtasham madrasadan iborat dunyoga mashhur me'moriy ansambl.",
    rating: 5.0,
    imageUrl: "/Samarkand-Registan-cinematic.jpeg",
    bestTimeToVisit: "Bahor va Kuz (Kechki chiroqlar bilan)",
  },
  {
    id: "a-2",
    name: "Ichan Qal'a (Ochiq Osmon Ostidagi Muzey)",
    cityName: "Xiva",
    categoryKey: "unesco",
    categoryDefault: "UNESCO Merosi",
    description: "O'rta asr osiyo shaharsozligining saqlanib qolgan yagona qadimiy devorlar bilan o'ralgan majmuasi.",
    rating: 4.9,
    imageUrl: "/Khiva-Ichan-Kala-aerial.jpeg",
    bestTimeToVisit: "Erta tong va Quyosh botishi",
  },
  {
    id: "a-3",
    name: "Poyi Kalon va Minora",
    cityName: "Buxoro",
    categoryKey: "historical",
    categoryDefault: "Tarixiy Obida",
    description: "47 metr balandlikdagi 1127-yilda qurilgan afsonaviy Kalon minorasi va Jome masjidi.",
    rating: 4.9,
    imageUrl: "/Bukhara-old-city-golden-hour.jpeg",
    bestTimeToVisit: "Oltin soat (Golden Hour)",
  },
  {
    id: "a-4",
    name: "Chorvoq Suv Ombori & Chimgon Tog'lari",
    cityName: "Toshkent viloyati",
    categoryKey: "nature",
    categoryDefault: "Tabiat & Hordiq",
    description: "Tog'lar bag'ridagi ko'k-mo'jiza ko'l va yil davomida faol bo'lgan kurort zonasi.",
    rating: 4.8,
    imageUrl: "/Charvak-Lake-drone.jpeg",
    bestTimeToVisit: "Yoz oylari va Qishki chang'i mavsumi",
  },
];

export const MOCK_RESTAURANTS: RestaurantItem[] = [
  {
    id: "r-1",
    name: "Besh Qozon (Osh Markazi)",
    cityName: "Toshkent",
    address: "Iftxor ko'chasi, 1-uy (Toshkent teleminorasi atrofi)",
    cuisine: "Milliy taomlar / Palov",
    rating: 4.9,
    reviewsCount: 1420,
    averageCheckSum: 65000,
    workingHours: "09:00 – 17:00",
    imageUrl: "/besh-qozon.jpg",
    phone: "+998 71 200 01 01",
  },
  {
    id: "r-2",
    name: "Platan Restaurant & Garden",
    cityName: "Samarqand",
    address: "Pushkin ko'chasi, 56",
    cuisine: "Yevropa va Sharq oshxonasi",
    rating: 4.8,
    reviewsCount: 680,
    averageCheckSum: 140000,
    workingHours: "11:00 – 23:00",
    imageUrl: "/platan-garden.jpg",
    phone: "+998 66 233 80 80",
  },
  {
    id: "r-3",
    name: "Chor Bakr Milliy Choyxonasi",
    cityName: "Buxoro",
    address: "Chor Bakr majmuasi yaqinida",
    cuisine: "Buxoro Somsa & Kabob",
    rating: 4.7,
    reviewsCount: 450,
    averageCheckSum: 85000,
    workingHours: "10:00 – 22:00",
    imageUrl: "/Bukhara-old-city-golden-hour.jpeg",
    phone: "+998 65 224 12 34",
  },
  {
    id: "r-4",
    name: "Muzey Choyxonasi (Ichan Kala)",
    cityName: "Xiva",
    address: "Ichan Qal'a markazi",
    cuisine: "Xorazm Tuxum-barak va Shivit Oshi",
    rating: 4.9,
    reviewsCount: 380,
    averageCheckSum: 95000,
    workingHours: "10:00 – 23:00",
    imageUrl: "/Khiva-Ichan-Kala-aerial.jpeg",
    phone: "+998 62 375 44 11",
  },
];

export const MOCK_TRANSPORTS: TransportItem[] = [
  {
    id: "t-1",
    name: "Chevrolet Cobalt (2024)",
    cityName: "Toshkent",
    categoryKey: "rent",
    categoryDefault: "Avto Ijarasi",
    seats: 5,
    hasDriver: false,
    fuelType: "Benzin/Metan",
    transmission: "Avtomat",
    pricePerDaySum: 350000,
    rating: 4.8,
    imageUrl: "/cobalt-car.jpg",
    phone: "+998 90 123 45 67",
  },
  {
    id: "t-2",
    name: "Kia K5 GT-Line (2024)",
    cityName: "Toshkent / Samarqand",
    categoryKey: "vip",
    categoryDefault: "VIP Taksi",
    seats: 4,
    hasDriver: true,
    fuelType: "Benzin 95",
    transmission: "Avtomat",
    pricePerDaySum: 850000,
    rating: 4.9,
    imageUrl: "/kiak5-car.jpg",
    phone: "+998 90 987 65 43",
  },
  {
    id: "t-3",
    name: "Mercedes-Benz Sprinter VIP",
    cityName: "Samarqand / Buxoro / Toshkent",
    categoryKey: "transfer",
    categoryDefault: "Aeroport Transfer",
    seats: 15,
    hasDriver: true,
    fuelType: "Dizel",
    transmission: "Avtomat",
    pricePerDaySum: 1500000,
    rating: 5.0,
    imageUrl: "/Bukhara-old-city-golden-hour.jpeg",
    phone: "+998 66 200 30 40",
  },
  {
    id: "t-4",
    name: "Chevrolet Tahoe Premier",
    cityName: "Toshkent / Samarqand",
    categoryKey: "vip",
    categoryDefault: "VIP & Biznes Taksi",
    seats: 7,
    hasDriver: true,
    fuelType: "Benzin",
    transmission: "Avtomat",
    pricePerDaySum: 2200000,
    rating: 4.9,
    imageUrl: "/Khiva-Ichan-Kala-aerial.jpeg",
    phone: "+998 71 500 00 00",
  },
  {
    id: "t-5",
    name: "Chevrolet Tracker Premier 2",
    cityName: "Toshkent",
    categoryKey: "rent",
    categoryDefault: "Avto Ijarasi",
    seats: 5,
    hasDriver: false,
    fuelType: "Benzin 95",
    transmission: "Avtomat",
    pricePerDaySum: 480000,
    rating: 4.8,
    imageUrl: "/Tashkent-city-skyline.jpeg",
    phone: "+998 93 111 22 33",
  },
  {
    id: "t-6",
    name: "Hyundai Staria VIP Lounge",
    cityName: "Toshkent / Aeroport",
    categoryKey: "transfer",
    categoryDefault: "Aeroport Transfer",
    seats: 7,
    hasDriver: true,
    fuelType: "Dizel",
    transmission: "Avtomat",
    pricePerDaySum: 1200000,
    rating: 4.95,
    imageUrl: "/Samarkand-Registan-cinematic.jpeg",
    phone: "+998 90 777 88 99",
  },
];
